// constants/ui.ts - Constantes de UI compartilhadas pelas telas (tema visual + categorias).
// Extraídas do antigo App.tsx monolítico durante o split da Fase 1.
import { CategoryType } from '../types';

export const themes = {
  emerald: {
    primary: 'bg-emerald-600',
    primaryHover: 'bg-emerald-700',
    text: 'text-emerald-600',
    border: 'border-emerald-600',
    light: 'bg-emerald-50',
    darkLight: 'dark:bg-emerald-900/20',
    gradient: 'from-emerald-500 to-emerald-600',
    bgGradient: 'from-emerald-50 to-green-50',
    accent: 'bg-emerald-100',
    shadow: 'shadow-emerald-100',
    focusRing: 'focus:ring-emerald-500',
  },
  blue: {
    primary: 'bg-blue-600',
    primaryHover: 'bg-blue-700',
    text: 'text-blue-600',
    border: 'border-blue-600',
    light: 'bg-blue-50',
    darkLight: 'dark:bg-blue-900/20',
    gradient: 'from-blue-500 to-blue-600',
    bgGradient: 'from-blue-50 to-indigo-50',
    accent: 'bg-blue-100',
    shadow: 'shadow-blue-100',
    focusRing: 'focus:ring-blue-500',
  },
  purple: {
    primary: 'bg-purple-600',
    primaryHover: 'bg-purple-700',
    text: 'text-purple-600',
    border: 'border-purple-600',
    light: 'bg-purple-50',
    darkLight: 'dark:bg-purple-900/20',
    gradient: 'from-purple-500 to-purple-600',
    bgGradient: 'from-purple-50 to-violet-50',
    accent: 'bg-purple-100',
    shadow: 'shadow-purple-100',
    focusRing: 'focus:ring-purple-500',
  },
  rose: {
    primary: 'bg-rose-600',
    primaryHover: 'bg-rose-700',
    text: 'text-rose-600',
    border: 'border-rose-600',
    light: 'bg-rose-50',
    darkLight: 'dark:bg-rose-900/20',
    gradient: 'from-rose-500 to-rose-600',
    bgGradient: 'from-rose-50 to-pink-50',
    accent: 'bg-rose-100',
    shadow: 'shadow-rose-100',
    focusRing: 'focus:ring-rose-500',
  },
};

export const categories = [
  { value: CategoryType.FOOD, label: 'Alimentação', icon: '🍽️' },
  { value: CategoryType.LEISURE, label: 'Lazer', icon: '🎉' },
  { value: CategoryType.TRANSPORT, label: 'Transporte', icon: '🚗' },
  { value: CategoryType.HOME, label: 'Casa', icon: '🏠' },
  { value: CategoryType.HEALTH, label: 'Saúde', icon: '🏥' },
  { value: CategoryType.PERSONAL, label: 'Pessoal', icon: '👤' },
  { value: CategoryType.EDUCATION, label: 'Educação', icon: '📚' },
  { value: CategoryType.SHOPPING, label: 'Compras', icon: '🛒' },
  { value: CategoryType.TRAVEL, label: 'Viagem', icon: '✈️' },
  { value: CategoryType.TECHNOLOGY, label: 'Tecnologia', icon: '💻' },
  { value: CategoryType.INVESTMENTS, label: 'Investimentos', icon: '📈' },
  { value: CategoryType.SALARY, label: 'Salário', icon: '💰' },
  { value: CategoryType.FREELANCE, label: 'Freelance', icon: '💼' },
  { value: CategoryType.BONUS, label: 'Bônus', icon: '🎁' },
  { value: CategoryType.DIVIDENDS, label: 'Dividendos', icon: '📊' },
  { value: CategoryType.RENT, label: 'Aluguel', icon: '🏢' },
  { value: CategoryType.SERVICES, label: 'Serviços', icon: '🔧' },
  { value: CategoryType.INSURANCE, label: 'Seguros', icon: '🛡️' },
  { value: CategoryType.TAXES, label: 'Impostos', icon: '📋' },
  { value: CategoryType.DONATIONS, label: 'Doações', icon: '❤️' },
  { value: CategoryType.OTHER, label: 'Outros', icon: '📝' },
];
